# Goreleaser config for Linux + Windows only (used by scripts/build-release-binaries-mac.sh).
# Darwin builds are done natively on the host. Requires goreleaser-cross + sysroot.

before:
  hooks:
    - go mod download

builds:
  - id: linux-amd64
    main: ./cmd/server
    binary: medha
    goos: [linux]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - "CGO_CFLAGS=--sysroot=/sysroot/linux/amd64 -I/sysroot/linux/amd64/usr/include"
      - "CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64 -L/sysroot/linux/amd64/usr/lib"
    flags: [-mod=readonly]
    ldflags: ["-s", "-w", "-X main.Version={{.Version}}"]

  - id: linux-arm64
    main: ./cmd/server
    binary: medha
    goos: [linux]
    goarch: [arm64]
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/arm64
      - "CGO_CFLAGS=--sysroot=/sysroot/linux/arm64 -I/sysroot/linux/arm64/usr/include"
      - "CGO_LDFLAGS=--sysroot=/sysroot/linux/arm64 -L/sysroot/linux/arm64/usr/lib"
    flags: [-mod=readonly]
    ldflags: ["-s", "-w", "-X main.Version={{.Version}}"]

  - id: windows-amd64
    main: ./cmd/server
    binary: medha
    goos: [windows]
    goarch: [amd64]
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    flags: [-mod=readonly]
    ldflags: ["-s", "-w", "-X main.Version={{.Version}}"]

archives:
  - id: default
    builds:
      - linux-amd64
      - linux-arm64
      - windows-amd64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true

checksum:
  name_template: checksums.txt

release:
  draft: false
